dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby
  - rbx-3
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
env:
  - JRUBY_OPTS='--debug'

